apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 07-deployments-dev
  namespace: argocd
  labels:
    level: tier-root
    tier: deployments
spec:
  project: default
  source:
    path: cwp/dev/alcide-installer-per-cluster
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-deploy.git
    targetRevision: HEAD
    directory:
      recurse: true

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc