apiVersion: v1
kind: ServiceAccount
metadata:
  name: "alcide-installer-ssm-sa"
  annotations:
    # https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
    eks.amazonaws.com/role-arn: arn:aws:iam::889956758113:role/alcide-installer-ssm-access