namespace : argocd
project: cwp-sass-dev-proj

alcide:
  repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/alcide
  destination:
    namespace: alcide
    server: https://3969BC3980538D1D0367E610E43745D6.sk1.eu-west-1.eks.amazonaws.com

external_secrets:
  repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
  destination:
    namespace: alcide
    server: https://kubernetes.default.svc