apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cwp-sass-dev-proj
  source:
    repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/new-structure/cluster-level-charts/
    chart: kubernetes-external-secrets
    targetRevision: 8.0.1
  destination:
    namespace: ops
    server: https://3EB3DC8AF129F3A4543FE2EF568D1494.yl4.eu-west-1.eks.amazonaws.com